version: "3.1"

services:
  webapp:
    image: lucassartori/web5:1.0
    container_name: my_rails_app
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
    tty: true
    links:
      - db

  db:
    image: postgres
    container_name: my_rails_db
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    tty: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  adminer:
    image: adminer
    container_name: rails_adminer
    ports:
      - 8080:8080
